---
title: "Megha's resume"
author: "Megha"
date: "`r Sys.Date()`"
output:
  pagedown::html_resume:
    # set it to true for a self-contained HTML page but it'll take longer to render
    self_contained: false
  knit: pagedown::knit_pdf_chrome
---

Aside
================================================================================




Contact Info {#contact}
--------------------------------------------------------------------------------

- <i class="fa fa-envelope"></i> megha.j456@utexas.edu
- <i class="fa fa-globe"></i> [meghapsimatrix.com](https://meghapsimatrix.com/)
- <i class="fa fa-github"></i> [github.com/meghapsimatrix](https://github.com/meghapsimatrix)
- <i class="fa fa-phone"></i> 469-235-3003
- For more information, please contact me via email.


Skills and Interests {#skills}
--------------------------------------------------------------------------------

- Statistical analysis and data vizualization

- Causal inference, experimental design, meta-analysis, and missing data analysis

- Machine learning

- R, Python, SQL, Git, Tableau

R Package {#package}
--------------------------------------------------------------------------------

[simhelpers 0.1.0](https://meghapsimatrix.github.io/simhelpers/index.html)

Disclaimer {#disclaimer}
--------------------------------------------------------------------------------

This resume was made with the R package [**pagedown**](https://github.com/rstudio/pagedown).

Last updated on `r Sys.Date()`.



Main
================================================================================

Megha Joshi {#title}
--------------------------------------------------------------------------------

Experienced statistician with strong background and interest in causal inference, meta-analysis, and missing data. 


Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

### The University of Texas at Austin

PhD in Quantitative Methods

Austin, TX

2020 (expected)

Advisors: Dr. Tasha Beretvas and Dr. James E. Pustejovsky

Thesis: Cluster wild bootstrapping to handle dependent effect sizes in meta-analysis with small number of studies

### The University of Texas at Austin

MEd in Quantitative Methods

Austin, TX

2017


### Bryn Mawr College

BA in Art History and Psychology

Bryn Mawr, PA

2014


Publications {data-icon=book}
--------------------------------------------------------------------------------

### [Direct ties to a faculty mentor related to positive outcomes for undergraduate researchers](https://doi.org/10.1093/biosci/biz039) 

_BioScience_, Volume 69, Issue 5, Pages 389–397

Austin, TX

2019

__Joshi, M.__, Aikens, M. L., & Dolan, E. L. 



### [The performance of multivariate methods for two-group comparisons with 	small samples and incomplete data](https://doi.org/10.1080/00273171.2019.1667217) 

_Multivariate Behavioral Research_, Pages 1-18

Austin, TX

2019

Pituch, K. A., __Joshi, M.__, Cain, M. E., Whittaker, T. A., Chang, W., Park, R., & McDougall, G. J. 


Technical Papers {data-icon=file}
--------------------------------------------------------------------------------

### [Evaluating the Transition to College Mathematics course in Texas high schools: Findings from the first year of implementation](https://www.greatertexasfoundation.org/wp-content/uploads/2019/06/Pustejovsky-Final-2019.pdf)

_Greater Texas Foundation_

Austin, TX

2019

Pustejovsky, J. E., & __Joshi, M.__ 


Conference Presentations {data-icon=group}
--------------------------------------------------------------------------------

### Cluster wild bootstrapping to handle dependent effect sizes in meta analyses with small numbers of studies

Poster session at the American Educational Research Association annual meeting

Toronto, Canada

2019

__Joshi, M.__, Cappelli, P., Pustejovsky, J. E., & Beretvas, S. N. 


### Small sample performance of multilevel and traditional methods for multivariate group comparisons with incomplete data


Roundtable session at the American Educational Research Association annual meeting

Toronto, Canada

2019

Pituch, K. A., Whittaker, T. A., __Joshi, M.__, Park, R., & Cain M. E.  





Work Experience {data-icon=laptop}
--------------------------------------------------------------------------------

### Graduate Research Assistant

The University of Texas at Austin 

Austin, TX

2020 - Present

_Supervisors: Dr. Pedro Reyes & Dr. Celeste D. Alexander_

- Assisted in an initiative started by Dean Charles Martinez to study the effects of Teacher Preparation Programs (TPPs) on teacher retention in Texas. 
- Integrated large relational datasets from the Texas Education Agency and the State Board for Educator Certification. Access to the data was provided by the UT [Education Research Center](https://texaserc.utexas.edu/). 
- Analyzed the impact of TPPs on employment and retention using linear probability model and survival analysis. 
- Collaborated with team members and delegated data-analytic tasks.


### Graduate Research Assistant

The University of Texas at Austin 

Austin, TX

2020 - Present

_Supervisor: Dr. Laura Costello_

- Created surveys to collect information on the impact of COVID-19 outbreak on students, faculty, and staff at the College of Education. 
- Generated reports to be disseminated to the College of Education.


### Graduate Research Assistant

The University of Texas at Austin 

Austin, TX

2017 - 2020

_Supervisor: Dr. James E. Pustejovsky_

- Evaluated the impact of a college preparatory program using propensity score analysis with generalized boosted modeling. 
- Integrated large relational datasets containing information on all students in Texas schools from multiple sources like the Texas Education Agency and the Texas Higher Education Coordinating Board. Access to the data was provided by the UT [Education Research Center](https://texaserc.utexas.edu/).
- Created technical reports on the findings; communicated findings to stakeholders.


### Graduate Research Assistant

The University of Texas at Austin 

Austin, TX

2016 

_Supervisor: Dr. Erin L. Dolan_

- Coordinated a research project on undergraduate research experiences.
- Designed a survey using Qualtrics and recruited over a thousand undergraduates nationwide to participate. 
-	Analyzed data using structural equation modeling.



### Integrated Community Development Intern

A Glimmer of Hope Foundation

Austin, TX

2015- 2016

_Supervisor: Leslie Llado_

- Analyzed data related to health, education, water, sanitation, and micro-finance projects carried out by the organization in Ethiopia.
- Developed a method to estimate the number of people who have benefited from the projects.


Teaching Experience {data-icon=chalkboard-teacher}
--------------------------------------------------------------------------------

### Graduate Teaching Assistant

The University of Texas at Austin

Austin, TX

2015 - Present

_Supervisors: Dr. James E. Pustejovsky, Dr. Keenan A. Pituch, Dr. Sarah M. Collins, Dr. Lindsey J. Smith_

- Assisted in the following courses: Causal Inference; Data Analysis, Simulation and Programming in R; Research Design; Survey of Multivariate Methods; Fundamental Statistics; and Statistics in Market Analysis.
- Effectively communicated complex statistical methods to students with little prior background in the field. 


Fellowships and Awards {data-icon=trophy}
--------------------------------------------------------------------------------


### Graduate School Continuing Fellowship 

The University of Texas at Austin

Austin, TX

2020-2021


### Teresa Lozano Long Endowed Graduate Fellowship

The University of Texas at Austin

Austin, TX

2019-2020

### Graduate Student Recruitment Fellowship

The University of Texas at Austin

Austin, TX

2017-2019


### Lee Hage and Joseph D. Jamail Endowed Scholarship in Education

The University of Texas at Austin

Austin, TX

2015-2016


### Benjamin Gilman International Scholarship

U.S. Department of State

Bryn Mawr, PA

2012


### Bryn Mawr College Grant

Bryn Mawr College

Bryn Mawr, PA

2010-2014


