---
title: "Megha's resume"
author: "Megha"
date: "`r Sys.Date()`"
output:
  pagedown::html_resume:
    # set it to true for a self-contained HTML page but it'll take longer to render
    self_contained: false
  knit: pagedown::knit_pdf_chrome
---

Aside
================================================================================




Contact Info {#contact}
--------------------------------------------------------------------------------

- <i class="fa fa-envelope"></i> megha.j456@utexas.edu
- <i class="fa fa-globe"></i> [meghapsimatrix.com](https://meghapsimatrix.com/)
- <i class="fa fa-github"></i> [github.com/meghapsimatrix](https://github.com/meghapsimatrix)
- <i class="fa fa-phone"></i> 469-235-3003
- For more information, please contact me via email.


Skills {#skills}
--------------------------------------------------------------------------------

- Statistical analysis and data vizualization

- Causal inference, experimental design, and missing data analysis

- Machine learning

- R, Python, SQL, Git, Tableau

R Package {#package}
--------------------------------------------------------------------------------

[simhelpers 0.1.0](https://meghapsimatrix.github.io/simhelpers/index.html)

Disclaimer {#disclaimer}
--------------------------------------------------------------------------------

This resume was made with the R package [**pagedown**](https://github.com/rstudio/pagedown).

Last updated on `r Sys.Date()`.



Main
================================================================================

Megha Joshi {#title}
--------------------------------------------------------------------------------

Experienced statistician with strong background in causal inference. I drive impact and growth by infusing teams with data-driven insights and scientifically-driven solutions. 


Experience {data-icon=laptop}
--------------------------------------------------------------------------------

### Graduate Research Assistant

The University of Texas at Austin 

Austin, Texas

2017 - Present

- Developed generalized boosted models to estimate propensity scores to evaluate the impact of a college preparatory program. 
- Integrated large relational datasets containing information on all students in Texas schools from multiple sources. Wrangled the data for analysis.

### Graduate Research Assistant

The University of Texas at Austin 

Austin, Texas

2018

- Developed propensity score models to evaluate School of Undergraduate Studies programs. 
- Created visualizations (R::ggplot) of impact analyses and automated creation of reports using R Markdown.
- Led a workshop on impact assessment.

### Integrated Community Development Intern

A Glimmer of Hope Foundation

Austin, Texas

2015- 2016

- Analyzed data related to health, education, water, sanitation, and micro-finance projects carried out by the organization in Ethiopia.
- Developed a method to estimate the number of people who have benefited from the projects.
  


Teaching Experience {data-icon=chalkboard-teacher}
--------------------------------------------------------------------------------

### Graduate Teaching Assistant

The University of Texas at Austin

Austin, Texas

2015 - Present

- Assisted in the following courses: Causal Inference; Data Analysis, Simulation, and Programming in R; Research Design; and, Statistics in Market Analysis. 
- Effectively communicated complex statistical methods to students with little prior background in the field. 


Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

### The University of Texas at Austin

PhD in Quantitative Methods

Austin, Texas

2020 (expected)

Thesis: Cluster wild bootstrapping to handle dependent effect sizes in meta-analysis


### Bryn Mawr College

BA in Art History and Psychology

Bryn Mawr, Pennsylvania

2014

